apiVersion: v1
kind: Secret
metadata:
  name: ops-version-backend-secret
type: Opaque
stringData:
  MYSQL_HOST: "__FILL__"
  MYSQL_PORT: "3306"
  MYSQL_USER: "__FILL__"
  MYSQL_PASSWORD: "__FILL__"
  MYSQL_DATABASE: "ops_version"
  ENCRYPT_KEY: "__GEN_ENCRYPT_KEY__"
  JWT_SECRET: "__GEN_JWT_SECRET__"
  SUPER_USER: "admin"
  SUPER_PASSWORD: "__FILL__"
  PORT: "8080"
  METRICS_PORT: "8088"
  COLLECT_INTERVAL_MIN: "30"
  LOG_LEVEL: "debug"
